{% set name = "dolfin-adjoint" %}
{% set version = "2017.1.0" %}
{% set sha256 = "01eac63c9efd92e69dc0c9f34714ef73b62678cf3d026a0319971fc032e81a44" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://bitbucket.org/{{ name }}/{{ name }}/downloads/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - python3.patch

build:
  number: 1
  script: python setup.py install
  skip: True  # [win]

requirements:
  build:
    - python
  run:
    - python
    - mpich
    - petsc 3.7.*
    - petsc4py 3.7.*
    - slepc 3.7.*
    - slepc4py 3.7.*
    - fenics 2017.1.*
    - libadjoint 2017.1.*

test:
  imports:
    - dolfin_adjoint
    - fenics_adjoint

about:
  home: http://www.dolfin-adjoint.org/
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: 'derives the discrete adjoint and tangent linear models'

  description: |
    The dolfin-adjoint project automatically derives the discrete adjoint
    and tangent linear models from a forward model written in the Python
    interface to DOLFIN.
  doc_url: http://www.dolfin-adjoint.org/en/latest/documentation/index.html
  dev_url: https://bitbucket.org/dolfin-adjoint/dolfin-adjoint

extra:
  recipe-maintainers:
    - johannesring
    - funsim
