{% set name = "dolfin-adjoint" %}
{% set version = "2023.0.0" %}
{% set sha256 = "809e30f37ad9fd14e5288aa092752ea83e6c2ee27e84359424c58ab7908b08e3" %}
{% set fenics_version = "2019.1.*" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dolfin-adjoint/dolfin-adjoint/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # patch merged upstream:

build:
  number: 0
  script: python -m pip install --no-deps .
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - fenics {{ fenics_version }}
    - moola >=0.1.6
    - scipy

test:
  requires:
    - pytest
  source_files:
    - test
  imports:
    - dolfin_adjoint
    - fenics_adjoint
    - pyadjoint
  commands:
    - pytest -vs tests/pyadjoint
    - pytest -vs tests/fenics_adjoint/test_optimization_scipy.py


about:
  home: https://www.dolfin-adjoint.org
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: 'derives the discrete adjoint and tangent linear models'

  description: |
    The dolfin-adjoint project automatically derives the discrete adjoint
    and tangent linear models from a forward model written in the Python
    interface to DOLFIN.
  doc_url: https://www.dolfin-adjoint.org/en/latest/documentation/index.html
  dev_url: https://github.org/dolfin-adjoint/dolfin-adjoint

extra:
  recipe-maintainers:
    - johannesring
    - funsim
    - minrk
