travis:
  secure:
    BINSTAR_TOKEN: GnXVmGOiJZgWBWpuMb4UQh4E+R3Bw/P8cF/N6IJcZ5qBmN0Pcn3G4LyJrcap9D8XqgJB8KhWFFsjJurervrZ+zPckvuOFlPl+dfkIKbSKdn9jGo2cCFv3qBi1pFr92nRI9vHl12lChl1QcSSFZkB45liKJYUbsD5S2+frqQc/tWbii/zDHaUrjtJ/VhUvjbs94sYpl9MwmvbuIYy462blaaWI2TS5dYRl44N4FOOI29kLf1FpyoqcJUpFGS/jisiTOO2ogB/PQDxBnCPgzHCkPRDJPvQkoIQJj0+r3A1XfeykrqdGsM0ils8wZpxZ0dIftt1Hp371DurTyPJjEISw6SS2YlEIxcijvaWfKgBkBccIxIze8JnMhUg1IFFFjSPzV9Th4Jfs7Jj9L50kg/yzd648JTSXwkVlF542LV7Tdj/UyXSnlWDCQ3wzc7kp7LBDtXhf5FsnAbVTDngcDfrfSDbkc4qYnbRJmAnnPYe5b09Va7yiCyjSX7r+0Ix9eiZBa398uC3QkVKanp5Gx75SsexzlztVbedErLaMKCNcMJbbfuO4qHg+6O6Hjpp0AEzVn4SAOVd6X6rQO2N5t06jCN0HEjIyaMkvbIOmDfbJKOXQl5qpbItcXBJo/tzDpdNSvarUuBJvtV4jDcNrrjhcqqLYxmcVIkHfOML4cfrtxY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
