travis:
  secure:
    BINSTAR_TOKEN: nB/CbVix6wkD2BMK+iTa4mpd1vQlfjKJB9O5g4FCkKCfXGZqBTIYN39k7c9pQZJXwgyAJi0L3fNmU9qsp/RBQm8X8bv2DvnUpKZ36KROIK/llNSnjK36IJSWelASjsw9vE7CJQp0fwGsJx6GEyGFWsl7Jlzr181u43nbXkWlltfBlzR5Hb5Z/d/zLM6h0rFTsViaQOGH8PxEqnDat92DnZY5CJW0O4vK7e4ZAu/HBVaIge1JnNQfaiZz3B/Z/wHa0zJMDEPXxn1okeBKkd5AsUs0I9FWswgyXJ4hGa5B7w0U9qAHA2hAMnyQhTg3cFQso5v8qVrhGgmgIZ3CAGinLqn/Et72NixHaQl2i6hC/zCQV0BD64cdMl+rsRoGTxe6nEO67bA5zRrcwvJxcfylXsJZr/wygzsi3C99JsHmgTKagNouPeRiuKyAhOmkRhd5Mj6fs1kXjZqtAcehWwzmdRrQE910XvZsaq/ZrDMtcMsxpkDsjuw0+GupcTeMwtPqrUH6QjuYo0wgfg5yyeUi7SbW+FVN0UxayPN5E0IpSpj9RvYPo4hMX7llFsW2oU0aD+t7yJUsdPKEN0HTm+WAHbriMG0H3aD0McOsTPhUFc//DFYMHSfh4J2kZ+KnggiblK1zXsq7QKFD2qhTDz2w7O7xLUfgLT0Ktie3tpBekrw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
